kind: Service
apiVersion: v1
metadata:
  name: vuejsui
  namespace: mongodb
  labels:
    app: vuejsui
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: vuejsui
  type: LoadBalancer