kind: Deployment
apiVersion: apps/v1
metadata:
  name: vuejsui
  namespace: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vuejsui
  template:
    metadata:
      labels:
        app: vuejsui
    spec:
      containers:
      - name: vuejsui
        image: gcr.io/kyudong-kim/vuejsui:2.0
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP